FROM node:22-bookworm

WORKDIR /app

RUN corepack enable
RUN apt-get update && apt-get install -y --no-install-recommends expect git && rm -rf /var/lib/apt/lists/*

COPY package.json pnpm-lock.yaml ./
COPY dist ./dist
COPY scripts ./scripts

RUN pnpm install --frozen-lockfile --ignore-scripts

CMD ["sh", "./scripts/test-build-cli.sh"]
